# Generated by Django 2.2.4 on 2020-12-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='radio',
            field=models.TextField(null=True),
        ),
    ]
