# Generated by Django 2.2.4 on 2020-12-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_apps', '0002_bookmodel_radio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='radio',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
