# Generated by Django 2.2.4 on 2020-12-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_apps', '0003_auto_20201209_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='md_auto_ext_radio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='md_e_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='md_e_wday',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='md_exclude_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='md_exclude_id_radio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='md_exclude_titledesc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='md_exclude_titledesc_radio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='md_rate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='md_rate_radio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='md_src_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='radio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
