# Generated by Django 2.2.4 on 2020-12-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_apps', '0004_auto_20201209_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_src_url', models.TextField(null=True)),
                ('md_e_wday', models.CharField(max_length=50, null=True)),
                ('md_e_time', models.CharField(max_length=50, null=True)),
                ('md_auto_ext', models.CharField(max_length=50, null=True)),
                ('md_rate', models.CharField(max_length=50, null=True)),
                ('md_exclude_id', models.TextField(null=True)),
                ('md_exclude_titledesc', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BookModel',
        ),
    ]
