# Generated by Django 2.2.4 on 2020-12-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_apps', '0006_searchquerymodel_md_query_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_analysis_pages',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
