# Generated by Django 2.2.4 on 2020-12-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_apps', '0007_searchquerymodel_md_analysis_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_exclude_id_radio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_exclude_titledesc_radio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_rate_radio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
