# Generated by Django 2.2.4 on 2020-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_apps', '0008_auto_20201210_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_seller_url',
            field=models.TextField(null=True),
        ),
    ]
