# Generated by Django 2.2.4 on 2020-12-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_apps', '0010_searchquerymodel_md_radio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_radio_e_wday_e_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
